### ISSUE TITLE
please help

### ISSUE THREAD

**Issue by cvkjm** [fdciabdul/mutasi-scraper#12]
saya coba2 gini terus mas, bisakah dibantu? terima kasih sebelumnya

Error: An `executablePath` or `channel` must be specified for `puppeteer-core`
    at assert (C:\tescuy3\node_modules\puppeteer-core\lib\cjs\puppeteer\util\assert.js:28:15)
    at ChromeLauncher.launch (C:\tescuy3\node_modules\puppeteer-core\lib\cjs\puppeteer\node\ChromeLauncher.js:92:36)
    at PuppeteerNode.launch (C:\tescuy3\node_modules\puppeteer-core\lib\cjs\puppeteer\node\PuppeteerNode.js:154:105)
    at PuppeteerExtra.launch (C:\tescuy3\node_modules\puppeteer-extra\dist\index.cjs.js:129:41)

Node.js v18.13.0

**Comment by Cloud-Dark** [comment]
coba turunin versi node js nya
mungkin versi 14

**Comment by fdciabdul** [comment]
fixed di versi 1.8.5 

silahkan di update mas
