### ISSUE TITLE
Scrap BNI muncul TypeError: newInjectedPage is not a function

### ISSUE THREAD

**Issue by 94maldini** [fdciabdul/mutasi-scraper#63]
Saya mengalami masalah di Scrap BNI, yg dapat error ini
```
TypeError: newInjectedPage is not a function
    at ScrapBNI.launchBrowser (D:\Aplikasi\Apps\node\bni-api\node_modules\mutasi-scraper\lib\BrowserClasses.js:55:27)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async ScrapBNI.login (D:\Aplikasi\Apps\node\bni-api\node_modules\mutasi-scraper\lib\bank\BNI.class.js:21:20)
    at async ScrapBNI.getStatement (D:\Aplikasi\Apps\node\bni-api\node_modules\mutasi-scraper\lib\bank\BNI.class.js:110:18)
    at async runScraping (D:\Aplikasi\Apps\node\bni-api\index.js:20:18)
TypeError: Cannot read properties of undefined (reading 'goto')
    at ScrapBNI.login (D:\Aplikasi\Apps\node\bni-api\node_modules\mutasi-scraper\lib\bank\BNI.class.js:22:18)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async ScrapBNI.getStatement (D:\Aplikasi\Apps\node\bni-api\node_modules\mutasi-scraper\lib\bank\BNI.class.js:110:18)
    at async runScraping (D:\Aplikasi\Apps\node\bni-api\index.js:20:18)
D:\Aplikasi\Apps\node\bni-api\node_modules\mutasi-scraper\lib\bank\BNI.class.js:111
    if (!page) throw new Error("Login failed");
                     ^
Error: Login failed
    at ScrapBNI.getStatement (D:\Aplikasi\Apps\node\bni-api\node_modules\mutasi-scraper\lib\bank\BNI.class.js:111:22)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async runScraping (D:\Aplikasi\Apps\node\bni-api\index.js:20:18)
```
dengan kode sebagai berikut
```javascript
const {
    ScrapBNI
} = require('mutasi-scraper');
const user = 'user';
const pass = 'pass';

async function runScraping() {
    const scraper = new ScrapBNI(user, pass, {
        headless: true, // true if needed
        args: [
            '--log-level=3',
            '--no-default-browser-check',
            '--disable-infobars',
            '--disable-web-security',
            '--disable-site-isolation-trials',
        ],
        // executablePath: 'google-chrome', path google chrome  (uncomment line ini jika tidak diperlukan)  tapi direkomendasikan menggunakan google chrome 
    });

    var result = await scraper.getStatement();
    console.log(result);
}

runScraping();
``` 
setiap saya jalankan muncul chrome tapi hanya 1 detik dan muncul error tersebut

yg saya pakai windows 10, nodejs v16.16.0

**Comment by fdciabdul** [comment]
thanks buat reportnya @94maldini langsung ku check and fix

**Comment by 94maldini** [comment]
sepertinya sudah tau penyebabnya permasalahan Login failed, karena akun saya tidak bisa dibuka lewat link `https://ibank.bni.co.id/MBAWeb/FMB` dan saya coba selalu tidak bisa login, tapi lewat link `https://ibank.bni.co.id/corp/AuthenticationController....` akun bisa login

![image](https://github.com/fdciabdul/mutasi-scraper/assets/45210886/1221534f-67f0-4e30-9952-4ac89fc82ba6)

**Comment by fdciabdul** [comment]
kalo gitu harus enable ibank mobile nya mas, sebenarnya saya ada juga untuk versi yang iBank desktop

**Comment by 94maldini** [comment]
enable ibank mobile harus ke cabang terdekatya? untuk iBank desktop pasti untuk yg berbayar ya 😊
